version: '3'

services:

    webexpe:
        container_name: sin3dlauncherinst
        image: sin3dlauncher
        restart: always
        volumes:
            - "./media:/usr/src/app/media" # get access to media files
        ports:
           - "${PORT:-8000}:8000"
        
        # only comment in case it will be necessary
        environment:
           WEB_PREFIX_URL: "${WEB_PREFIX_URL:-}"