version: '3'

services:

    webexpe:
        container_name: sin3dlauncherinst
        image: sin3dlauncher
        restart: always
        volumes:
            - "./media:/usr/src/app/media" # get access to media files
        ports:
           - "8000:8000"
        
        # only comment in case it will be necessary
        # environment:
        #    WEBEXPE_PREFIX_URL: "${WEBEXPE_PREFIX_URL:-}"
        #    WEB_API_PREFIX_URL: "${WEB_API_PREFIX_URL:-api}"